
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: GH Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: cat README.md       
      - run: echo "Testing Release" > README.md
      - id: archive-code      
        name: Archive code
        run: |
          repoName=$(echo "`basename ${{ github.repository }}`")
          echo "repo name is $repoName"
          mkdir -p release_assets
          # Create a tarball (tgz) and a zip file of your code
          tar --exclude='release_assets' -czvf release_assets/${{ github.ref }}.tar.gz .
          zip -r release_assets/${{ github.ref }}.zip . -x "release_assets/*"
          echo "value=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
      - name: Create Release
        run: |
          if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref_type }}" == "tag" ]; then
            gh release create ${{ github.ref }} --generate-notes --latest ./release_assets/*.tar.gz ./release_assets/*.zip 
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_REPO_NAME: ${{ steps.archive-code.outputs.value }}

