
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: cat README.md       
      - run: echo "Testing Release" > README.md
      - run: cat README.md       
      - name: Create Release
        run: |
         gh release create $TAG --generate-notes
        env:
          TAG: ${{ github.ref }} 
